apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: martinenzinger/udagram-api-feed
        envFrom:
        - configMapRef:
            name: udagram-config
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
